/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as ApiPublicDumpRouteImport } from './routes/api/public/_dump'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDumpRoute = ApiPublicDumpRouteImport.update({
  id: '/api/public/_dump',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public': typeof ApiPublicDumpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public': typeof ApiPublicDumpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/_dump': typeof ApiPublicDumpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiences/$slug' | '/projects/$slug' | '/api/public'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiences/$slug' | '/projects/$slug' | '/api/public'
  id:
    | '__root__'
    | '/'
    | '/experiences/$slug'
    | '/projects/$slug'
    | '/api/public/_dump'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ApiPublicDumpRoute: typeof ApiPublicDumpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/_dump': {
      id: '/api/public/_dump'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ApiPublicDumpRoute: ApiPublicDumpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
